{
 "title": "API Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "api", "query": "label_values(name)" }
  ]
 },
 "panels": [
  { "title": "$api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "api" },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_health_check_status{name=\"$api\"}"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum(http_health_check_status{name=\"$api\"}) * 100 / (count(http_health_check_status{name=\"$api\"}))"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Status" }
   ],
   "targets": [
    {
     "expr": "http_health_check_status{name=~\"$api\"}",
     "legendFormat": "{{name}} status"
    },
    {
     "expr": "http_health_check_response_time{name=~\"$api\"}",
     "legendFormat": "{{name}} response time"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "http_health_check_status{name=~\"$api\", reason!=\"\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "$api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_health_check_status{name=\"$api\"}"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_health_check_status{name=\"$api\"}) * 100 / (count(http_health_check_status{name=\"$api\"}))"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Status" }
   ],
   "targets": [
    {
     "expr": "http_health_check_status{name=~\"$api\"}",
     "legendFormat": "{{name}} status"
    },
    {
     "expr": "http_health_check_response_time{name=~\"$api\"}",
     "legendFormat": "{{name}} response time"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "http_health_check_status{name=~\"$api\", reason!=\"\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}